### ISSUE TITLE
Support the registration of new accounts with OpenID Attribute Exchange

### ISSUE THREAD

**Issue by rmburkhead** [zikula-modules/OpenID#1]
== Description of the new feature ==

If a user attempts to log in with an OpenID of any flavor, and the user does not already have an account registered with the system, then there is no opportunity for the user to register a new account as part of the process. Instead, the user's authentication fails (because the OpenID specified by the user is not associated with an existing account).

Instead, if an OpenID is specified that is not associated with an existing user account, then the user should be offered two options:
1. The user should be informed that if he already has an existing user account, that in order to associate this unassociated OpenID he must first log in using an already registered authentication method.
2. The user should be offered the opportunity to complete the registration process for a new account, filling in the registration form fields with appropriate data gathered via the OpenID Attribute Exchange process after the OpenID has been authenticated.

Note: This requires that the Users module:
- not require a password in order to register a new account;
- support the association of an OpenID with a user account during the registration process.

In addition, the OpenID module will need to handle registration events so that if a registration request is rejected (assuming that registrations are moderated) or otherwise deleted (e.g., because an e-mail address was never verified) the associated OpenID can be deleted.

== Feature Benefits ==

This allows a site to run entirely using OpenIDs for authentication (with the exception of the default administrative user). It also improves the new user experience by allowing him to fully use the benefits of his OpenID, rather than requiring that a standard Users module user name and password first be established before an OpenID can be used to log in.

**Comment by cmfcmf** [comment]
**Update**
- [ ] The user should be informed that if he already has an existing user account, that in order to associate this unassociated OpenID he must first log in using an already registered authentication method. **[see https://github.com/zikula/core/issues/901]**
  - https://github.com/rojblake/ADLibrary/commit/08d5d866487277338f003c1967a22d3f4b5aefa7#L1R341
- [x] The user should be offered the opportunity to complete the registration process for a new account **[see https://github.com/zikula/core/issues/901] [fixed in https://github.com/zikula/core/pull/1407] DONE**
- [x] **DONE [#21]** filling in the registration form fields with appropriate data gathered via the OpenID Attribute Exchange process after the OpenID has been authenticated. _Interesting lines:_
  - https://github.com/zikula/core/blob/1.3/src/system/Zikula/Module/UsersModule/Controller/UserController.php#L355
  - https://github.com/zikula/core/blob/1.3/src/system/Zikula/Module/UsersModule/Controller/UserController.php#L376
  - https://github.com/rojblake/ADLibrary/commit/08d5d866487277338f003c1967a22d3f4b5aefa7#L1R341
- [x] not require a password in order to register a new account; **DONE**
- [x] support the association of an OpenID with a user account during the registration process. **DONE**
- [x] In addition, the OpenID module will need to handle registration events so that if a registration request is rejected (assuming that registrations are moderated) or otherwise deleted (e.g., because an e-mail address was never verified) the associated OpenID can be deleted. **DONE via the registration delete and user delete listener… will check this**
